import { ProductContextProvider } from "./ContextProvider";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout component
export default function RootLayout({ children }) {
  // Array of product objects
  const products = [
    {
      id: 1,
      title: "Essence Mascara Lash Princess",
      category: "beauty",
      price: 9.99,
      rating: 4.94,
      stock: 0,
      brand: "Essence",
      images: [
        "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/1.png"
      ],
      thumbnail:
        "https://cdn.dummyjson.com/products/images/beauty/Essence%20Mascara%20Lash%20Princess/thumbnail.png",
    },
    {
      id: 2,
      title: "Eyeshadow Palette with Mirror",
      category: "beauty",
      price: 19.99,
      rating: 3.28,
      stock: 44,
      brand: "Glamour Beauty",
      images: [
        "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/1.png"
      ],
      thumbnail:
        "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png",
    },
    {
      id: 3,
      title: "Powder Canister",
      category: "beauty",
      price: 14.99,
      rating: 3.82,
      stock: 59,
      brand: "Velvet Touch",
      images: [
        "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/1.png"
      ],
      thumbnail:
        "https://cdn.dummyjson.com/products/images/beauty/Powder%20Canister/thumbnail.png",
    },
    {
      id: 4,
      title: "Red Lipstick",
      category: "beauty",
      price: 12.99,
      rating: 2.51,
      stock: 68,
      brand: "Chic Cosmetics",
      images: [
        "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/1.png"
      ],
      thumbnail:
        "https://cdn.dummyjson.com/products/images/beauty/Red%20Lipstick/thumbnail.png",
    },
    {
      id: 5,
      title: "Red Nail Polish",
      category: "beauty",
      price: 8.99,
      rating: 3.91,
      stock: 71,
      brand: "Nail Couture",
      images: [
        "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/1.png"
      ],
      thumbnail:
        "https://cdn.dummyjson.com/products/images/beauty/Red%20Nail%20Polish/thumbnail.png",
    },
    {
      id: 6,
      title: "Calvin Klein CK One",
      category: "fragrances",
      price: 49.99,
      rating: 4.85,
      stock: 17,
      brand: "Calvin Klein",
      images: [
        "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/1.png"
      ],
      thumbnail:
        "https://cdn.dummyjson.com/products/images/fragrances/Calvin%20Klein%20CK%20One/thumbnail.png",
    },
  ];

  return (
    <html lang="en">
      <head>
        <title>NovaNest</title>
      </head>
      <body>
        <ProductContextProvider value={products}>
          {children}
        </ProductContextProvider>
      </body>
    </html>
  );
}
